export const endPoints = {
    fetch_music_json : '/fetch_music_json',
    info_record:'/info_record',
    fetch_unique_music_json:'/fetch_unique_music_json',
    fetch_latest_songs:'/fetch_latest_songs',
    download_records_With_Out_UserId:'/download_records_With_UserId',
    login:'/login2',
    browse2:'/browse2',
    update_Date_in_download_history:'/update_Date_in_download_history',
    update_copyright:'/update_copyright',
    fetch_playlist2:'fetch_playlist2',
    fetch_data2:'/fetch_data2',
    add_to_fav2:'/add_to_fav2',
    fetch_data_favorites:'/fetch_data_favorites',
    add_playlist:'/add_playlist',
    signup:'/signup',
    profile:'/profile',
    update_profile:'/update_profile',
    pricing:'/pricing',
    select_plan: 'pricing/selectPlan',
    oauth_provider: 'oauth',
    billing: 'billing',
    current_plan: 'current_plan',
    contact_submit: 'contact_submit',
    submit_payment: 'submit_payment',
    download:'/download',
    update_payment: 'update_payment',
    add_new_payment_method: 'add',
    submit_music_api:'submit_music_api',
    pay:'pay',
    sim_song: 'sim_song',
    copyright_clearance: 'copyright_clearance'
  };
  